import { NextResponse } from "next/server";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { ensureRentACarSchema } from "@/lib/rentacar-schema";

type TipoPersona="PROSPECTO"|"CLIENTE";
type Row={id:string;numeroOrden:string;prospectoId:string|null;clienteId:string|null;tipoPersona:TipoPersona;personaNombre:string;recogidaIata:string;entregaIata:string;mismaEntrega:boolean;fechaRecogida:string;horaRecogida:string;fechaEntrega:string;horaEntrega:string;tipoVehiculo:string;seguro:string;detalles:string|null;estado:"PENDIENTE"|"DESPACHADA";creadoPorNombre:string;createdAt:string;despachadoAt:string|null};
const VEHICULOS=["Economico","Compacto","Small SUV","Medium SUV","Full Size SUV","VAN","Extended VAN","Convertible"];
const SEGUROS=["Basico","Cobertura terceros","Completo"];
function tp(v:unknown):TipoPersona{return v==="CLIENTE"?"CLIENTE":"PROSPECTO"}
function iata(v:unknown){return typeof v==="string"?v.trim().toUpperCase():""}

export async function GET(){try{await ensureRentACarSchema();const ordenes=await db.$queryRaw<Row[]>`
SELECT o."id",o."numeroOrden",o."prospectoId",o."clienteId",CASE WHEN o."clienteId" IS NOT NULL THEN 'CLIENTE' ELSE 'PROSPECTO' END AS "tipoPersona",CASE WHEN o."clienteId" IS NOT NULL THEN CONCAT(c."nombres",' ',c."apellidos") ELSE CONCAT(p."nombres",CASE WHEN p."apellidos" IS NOT NULL AND p."apellidos"<>'' THEN CONCAT(' ',p."apellidos") ELSE '' END) END AS "personaNombre",o."recogidaIata",o."entregaIata",o."mismaEntrega",o."fechaRecogida"::text,o."horaRecogida",o."fechaEntrega"::text,o."horaEntrega",o."tipoVehiculo",o."seguro",o."detalles",o."estado",u."name" AS "creadoPorNombre",o."createdAt"::text,o."despachadoAt"::text FROM "orden_cotizacion_rentacar" o LEFT JOIN "prospecto" p ON p."id"=o."prospectoId" LEFT JOIN "cliente" c ON c."id"=o."clienteId" INNER JOIN "user" u ON u."id"=o."creadoPorId" WHERE (o."prospectoId" IS NULL OR p."deletedAt" IS NULL) AND (o."clienteId" IS NULL OR (c."deletedAt" IS NULL AND c."activo"=true)) ORDER BY o."createdAt" DESC`;return NextResponse.json({ordenes})}catch(e){console.error(e);return NextResponse.json({error:"No se pudieron obtener las órdenes de Rent a Car"},{status:500})}}

export async function POST(request:Request){try{await ensureRentACarSchema();const s=await auth.api.getSession({headers:await headers()});if(!s?.user?.id)return NextResponse.json({error:"No autorizado"},{status:401});const b=await request.json();const tipoPersona=tp(b.tipoPersona),personaId=typeof b.personaId==="string"?b.personaId.trim():"",recogida=iata(b.recogidaIata),misma=b.mismaEntrega===true,entrega=misma?recogida:iata(b.entregaIata),fechaRecogida=typeof b.fechaRecogida==="string"?b.fechaRecogida:"",horaRecogida=typeof b.horaRecogida==="string"?b.horaRecogida:"",fechaEntrega=typeof b.fechaEntrega==="string"?b.fechaEntrega:"",horaEntrega=typeof b.horaEntrega==="string"?b.horaEntrega:"",tipoVehiculo=typeof b.tipoVehiculo==="string"?b.tipoVehiculo:"",seguro=typeof b.seguro==="string"?b.seguro:"",detalles=typeof b.detalles==="string"&&b.detalles.trim()?b.detalles.trim():null;
if(!personaId)return NextResponse.json({error:"Selecciona prospecto o cliente"},{status:400});if(!/^[A-Z]{3}$/.test(recogida)||!/^[A-Z]{3}$/.test(entrega))return NextResponse.json({error:"Selecciona lugares de recogida y entrega válidos"},{status:400});if(!fechaRecogida||!fechaEntrega||!horaRecogida||!horaEntrega)return NextResponse.json({error:"Completa fechas y horas"},{status:400});const inicio=new Date(`${fechaRecogida}T${horaRecogida}`),fin=new Date(`${fechaEntrega}T${horaEntrega}`);if(Number.isNaN(inicio.getTime())||Number.isNaN(fin.getTime())||fin<=inicio)return NextResponse.json({error:"La entrega debe ser posterior a la recogida"},{status:400});if(!VEHICULOS.includes(tipoVehiculo))return NextResponse.json({error:"Tipo de vehículo no válido"},{status:400});if(!SEGUROS.includes(seguro))return NextResponse.json({error:"Seguro no válido"},{status:400});let prospectoId:string|null=null,clienteId:string|null=null;if(tipoPersona==="CLIENTE"){const c=await db.cliente.findFirst({where:{id:personaId,deletedAt:null,activo:true},select:{id:true}});if(!c)return NextResponse.json({error:"Cliente no disponible"},{status:404});clienteId=c.id}else{const p=await db.prospecto.findFirst({where:{id:personaId,deletedAt:null},select:{id:true}});if(!p)return NextResponse.json({error:"Prospecto no disponible"},{status:404});prospectoId=p.id}
const anio=new Date().getFullYear(),id=crypto.randomUUID();const creada=await db.$transaction(async tx=>{const c=await tx.$queryRaw<Array<{ultimo:number}>>`INSERT INTO "orden_cotizacion_rentacar_contador" ("anio","ultimo") VALUES (${anio},1) ON CONFLICT ("anio") DO UPDATE SET "ultimo"="orden_cotizacion_rentacar_contador"."ultimo"+1 RETURNING "ultimo"`;const numeroOrden=`RAC-${anio}-${String(Number(c[0]?.ultimo??1)).padStart(4,"0")}`;const rows=await tx.$queryRaw<Row[]>`INSERT INTO "orden_cotizacion_rentacar" ("id","numeroOrden","prospectoId","clienteId","recogidaIata","entregaIata","mismaEntrega","fechaRecogida","horaRecogida","fechaEntrega","horaEntrega","tipoVehiculo","seguro","detalles","estado","creadoPorId","createdAt","updatedAt") VALUES (${id},${numeroOrden},${prospectoId},${clienteId},${recogida},${entrega},${misma},${fechaRecogida}::date,${horaRecogida},${fechaEntrega}::date,${horaEntrega},${tipoVehiculo},${seguro},${detalles},'PENDIENTE',${s.user.id},NOW(),NOW()) RETURNING "id","numeroOrden","prospectoId","clienteId",${tipoPersona} AS "tipoPersona",'' AS "personaNombre","recogidaIata","entregaIata","mismaEntrega","fechaRecogida"::text,"horaRecogida","fechaEntrega"::text,"horaEntrega","tipoVehiculo","seguro","detalles","estado",${s.user.name??"—"} AS "creadoPorNombre","createdAt"::text,"despachadoAt"::text`;return rows[0]});return NextResponse.json({orden:creada},{status:201})}catch(e){console.error(e);return NextResponse.json({error:"No se pudo crear la orden de Rent a Car"},{status:500})}}
