"use client";
import{useEffect,useState}from"react";import{CalendarClock,CheckCircle2,RefreshCw,Send}from"lucide-react";import{Badge}from"@/components/ui/badge";import{Button}from"@/components/ui/button";import{Input}from"@/components/ui/input";import{Label}from"@/components/ui/label";import{Textarea}from"@/components/ui/textarea";import{confirmarPagoArancel,obtenerEstadoArancel,reenviarHojaArancel,registrarEnvioHojaArancel,type ArancelEstadoNexus}from"@/lib/actions/tramites/arancel-actions";import{toast}from"sonner";

function nowLocal(){const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16)}
export function ArancelNexusCard({tramiteId}:{tramiteId:string}){const[data,setData]=useState<ArancelEstadoNexus|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[fecha,setFecha]=useState(nowLocal()),[obs,setObs]=useState("");
 async function cargar(){setLoading(true);const r=await obtenerEstadoArancel(tramiteId);if(r.success)setData(r.data??null);else toast.error(r.error);setLoading(false)}useEffect(()=>{void cargar()},[tramiteId]);
 async function primerEnvio(){if(!fecha)return toast.error("Registra la fecha y hora de envío");setSaving(true);const r=await registrarEnvioHojaArancel(tramiteId,fecha,obs);setSaving(false);if(!r.success)return toast.error(r.error);toast.success("Hoja de pago enviada · seguimiento programado en 24 horas");setObs("");await cargar()}
 async function confirmar(){setSaving(true);const r=await confirmarPagoArancel(tramiteId);setSaving(false);if(!r.success)return toast.error(r.error);toast.success("Pago recibido confirmado · ya puede programarse la cita");await cargar()}
 async function reenviar(){if(!fecha)return toast.error("Registra la nueva fecha y hora de envío");setSaving(true);const r=await reenviarHojaArancel(tramiteId,fecha,obs);setSaving(false);if(!r.success)return toast.error(r.error);toast.success("Hoja reenviada · nuevo seguimiento en 24 horas");setObs("");await cargar()}
 const pagado=data?.estado==="PAGADO",cumplio24h=!!data&&new Date(data.venceAt).getTime()<=Date.now();return <div className="rounded-xl border border-amber-300 bg-amber-50/40 p-4 space-y-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold">Hoja de Pago de Arancel</p><p className="mt-1 text-xs text-muted-foreground">Registra el envío real de la hoja. NEXUS habilita seguimiento después de 24 horas y lo muestra en Dashboard Time hasta confirmar el pago.</p></div><Badge variant={pagado?"default":data?"secondary":"outline"}>{pagado?"PAGADO":data?.estado??"SIN ENVÍO"}</Badge></div>{loading?<p className="text-sm text-muted-foreground">Cargando seguimiento...</p>:<>{data&&<div className="rounded-lg border bg-background/70 p-3 text-sm"><div className="flex gap-2"><CalendarClock className="mt-0.5 h-4 w-4"/><div><p><b>Último envío:</b> {new Date(data.fechaEnvio).toLocaleString("es-BO")}</p><p><b>Seguimiento desde:</b> {new Date(data.venceAt).toLocaleString("es-BO")}</p>{!pagado&&!cumplio24h&&<p className="mt-1 text-xs text-amber-700">La confirmación de pago se habilitará al cumplirse 24 horas desde el envío.</p>}{!pagado&&cumplio24h&&<p className="mt-1 text-xs text-amber-700">Seguimiento activo. Mantendrá pendiente hasta confirmar pago recibido o registrar un reenvío.</p>}{data.observacion&&<p><b>Observación:</b> {data.observacion}</p>}{data.ultimoUsuario&&<p className="text-xs text-muted-foreground">Registrado por {data.ultimoUsuario}</p>}{data.pagoConfirmadoAt&&<p className="mt-1 text-green-700"><CheckCircle2 className="mr-1 inline h-4 w-4"/>Pago confirmado {new Date(data.pagoConfirmadoAt).toLocaleString("es-BO")}</p>}</div></div></div>}{!pagado&&<><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label>{data?"Nueva fecha/hora de reenvío":"Fecha/hora de envío"}</Label><Input type="datetime-local" value={fecha} onChange={e=>setFecha(e.target.value)}/></div><div className="space-y-2"><Label>Observación</Label><Textarea rows={2} value={obs} onChange={e=>setObs(e.target.value)} placeholder={data?"Motivo del reenvío / cliente no pagó / incidencia":"Ej. hoja enviada por WhatsApp"}/></div></div><div className="flex flex-wrap gap-2">{!data?<Button type="button" size="sm" disabled={saving} onClick={()=>void primerEnvio()}><Send className="mr-2 h-4 w-4"/>Registrar envío de hoja</Button>:<><Button type="button" size="sm" disabled={saving||!cumplio24h} onClick={()=>void confirmar()}><CheckCircle2 className="mr-2 h-4 w-4"/>Confirmar pago recibido</Button><Button type="button" size="sm" variant="outline" disabled={saving} onClick={()=>void reenviar()}><RefreshCw className="mr-2 h-4 w-4"/>Reenviar hoja</Button></>}</div></>}</>}</div>}
