"use server";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { ensureDs160Schema, ESTADOS_DS160, type EstadoDs160 } from "@/lib/ds160-schema";
import type { ActionResult } from "@/types/action-result-types";

export type Ds160Data={applicationId:string|null;respuestaSeguridad:string|null;estado:EstadoDs160;actualizadoPorNombre:string|null;updatedAt:Date|null};
export async function obtenerDs160(tramiteId:string):Promise<ActionResult<Ds160Data>>{try{await ensureDs160Schema();const rows=await db.$queryRaw<Array<{applicationId:string|null;respuestaSeguridad:string|null;estado:string;actualizadoPorNombre:string|null;updatedAt:Date}>>`SELECT d."applicationId",d."respuestaSeguridad",d."estado",u."name" AS "actualizadoPorNombre",d."updatedAt" FROM "tramite_ds160" d LEFT JOIN "user" u ON u."id"=d."actualizadoPorId" WHERE d."tramiteId"=${tramiteId} LIMIT 1`;const d=rows[0];if(!d)return{success:true,data:{applicationId:null,respuestaSeguridad:null,estado:"INICIADO",actualizadoPorNombre:null,updatedAt:null}};return{success:true,data:{...d,estado:d.estado as EstadoDs160}}}catch(e){console.error("obtenerDs160",e);return{success:false,error:"Error al obtener DS-160"}}}
export async function guardarDs160(tramiteId:string,input:{applicationId:string;respuestaSeguridad:string;estado:EstadoDs160}):Promise<ActionResult<void>>{try{await ensureDs160Schema();const session=await auth.api.getSession({headers:await headers()});if(!session?.user?.id)return{success:false,error:"No autorizado"};const applicationId=input.applicationId.trim().toUpperCase();if(applicationId&&!/^AA00[A-Z0-9]+$/.test(applicationId))return{success:false,error:"El Application ID debe comenzar con AA00"};if(!(ESTADOS_DS160 as readonly string[]).includes(input.estado))return{success:false,error:"Estado DS-160 no válido"};await db.$executeRaw`INSERT INTO "tramite_ds160" ("tramiteId","applicationId","respuestaSeguridad","estado","actualizadoPorId","createdAt","updatedAt") VALUES (${tramiteId},${applicationId||null},${input.respuestaSeguridad.trim()||null},${input.estado},${session.user.id},NOW(),NOW()) ON CONFLICT ("tramiteId") DO UPDATE SET "applicationId"=EXCLUDED."applicationId","respuestaSeguridad"=EXCLUDED."respuestaSeguridad","estado"=EXCLUDED."estado","actualizadoPorId"=EXCLUDED."actualizadoPorId","updatedAt"=NOW()`;if(applicationId)await db.tramite.update({where:{id:tramiteId},data:{codigoConfirmacionDs160:applicationId}});return{success:true}}catch(e){console.error("guardarDs160",e);return{success:false,error:"Error al guardar DS-160"}}}
