// src/lib/actions/tramites/servicios-actions.ts
"use server";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import type { ActionResult } from "@/types/action-result-types";
import { type CambiarEstadoPagoFormData,type CreateClienteServicioFormData,cambiarEstadoPagoSchema,createClienteServicioSchema,type UpdateClienteServicioFormData,updateClienteServicioSchema } from "@/validations/tramite-validations";
export type ServicioCatalogo={id:string;nombre:string;codigo:string;requiereTramite:boolean;precioRegion:number|null};
export type ClienteServicioItem={id:string;precioAcordado:number;descuentoAplicado:number|null;precioFinal:number;notas:string|null;createdAt:Date;servicio:{id:string;nombre:string;codigo:string;requiereTramite:boolean};estadoPago:{id:string;nombre:string;color:string|null};tramite:{id:string;estadoActual:{nombre:string;color:string|null}}|null};
export async function obtenerCatalogosServicioConPrecio(regionId:string):Promise<ActionResult<ServicioCatalogo[]>>{try{const servicios=await db.catalogoServicio.findMany({where:{activo:true},include:{preciosPorRegion:{where:{regionId,activo:true},take:1}},orderBy:{orden:"asc"}});return{success:true,data:servicios.map(s=>({id:s.id,nombre:s.nombre,codigo:s.codigo,requiereTramite:s.requiereTramite,precioRegion:s.preciosPorRegion[0]?Number(s.preciosPorRegion[0].precio):null}))}}catch(e){console.error(e);return{success:false,error:"Error al obtener los servicios"}}}
export async function obtenerServiciosDeCliente(clienteId:string):Promise<ActionResult<ClienteServicioItem[]>>{try{const servicios=await db.clienteServicio.findMany({where:{clienteId,deletedAt:null},include:{servicio:{select:{id:true,nombre:true,codigo:true,requiereTramite:true}},estadoPago:{select:{id:true,nombre:true,color:true}},tramites:{where:{deletedAt:null},include:{estadoActual:{select:{nombre:true,color:true}}},take:1,orderBy:{createdAt:"desc"}}},orderBy:{createdAt:"desc"}});return{success:true,data:servicios.map(s=>({id:s.id,precioAcordado:Number(s.precioAcordado),descuentoAplicado:s.descuentoAplicado?Number(s.descuentoAplicado):null,precioFinal:Number(s.precioFinal),notas:s.notas,createdAt:s.createdAt,servicio:s.servicio,estadoPago:s.estadoPago,tramite:s.tramites[0]?{id:s.tramites[0].id,estadoActual:s.tramites[0].estadoActual}:null}))}}catch(e){console.error(e);return{success:false,error:"Error al obtener los servicios"}}}
export async function crearClienteServicio(input:CreateClienteServicioFormData):Promise<ActionResult<{id:string;requiereTramite:boolean}>>{try{const v=createClienteServicioSchema.parse(input);const servicio=await db.catalogoServicio.findUnique({where:{id:v.servicioId}});if(!servicio)return{success:false,error:"Servicio no encontrado"};const cs=await db.clienteServicio.create({data:{clienteId:v.clienteId,servicioId:v.servicioId,precioAcordado:v.precioAcordado,descuentoAplicado:v.descuentoAplicado??null,precioFinal:v.precioFinal,estadoPagoId:v.estadoPagoId,notas:v.notas??null}});return{success:true,data:{id:cs.id,requiereTramite:servicio.requiereTramite}}}catch(e){console.error(e);return{success:false,error:"Error al contratar el servicio"}}}
export async function actualizarClienteServicio(id:string,input:UpdateClienteServicioFormData):Promise<ActionResult<void>>{try{const v=updateClienteServicioSchema.parse(input);await db.clienteServicio.update({where:{id},data:v});return{success:true}}catch(e){console.error(e);return{success:false,error:"Error al actualizar el servicio"}}}
async function ensureCambio(){await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "cliente_servicio_cambio_nexus" ("id" TEXT PRIMARY KEY,"clienteServicioId" TEXT NOT NULL REFERENCES "cliente_servicio"("id") ON DELETE CASCADE,"servicioAnteriorId" TEXT NOT NULL,"servicioNuevoId" TEXT NOT NULL,"precioAnterior" DECIMAL(12,2) NOT NULL,"precioNuevo" DECIMAL(12,2) NOT NULL,"motivo" TEXT,"usuarioId" TEXT REFERENCES "user"("id") ON DELETE SET NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP)`)}
export async function cambiarServicioContratado(input:{clienteServicioId:string;servicioNuevoId:string;precioNuevo:number;motivo?:string|null}):Promise<ActionResult<void>>{try{await ensureCambio();const s=await auth.api.getSession({headers:await headers()});if(!s?.user?.id)return{success:false,error:"No autorizado"};const actual=await db.clienteServicio.findUnique({where:{id:input.clienteServicioId},include:{servicio:true}});if(!actual)return{success:false,error:"Servicio contratado no encontrado"};const nuevo=await db.catalogoServicio.findUnique({where:{id:input.servicioNuevoId}});if(!nuevo)return{success:false,error:"Nuevo servicio no encontrado"};const p=Number(input.precioNuevo);if(!Number.isFinite(p)||p<0)return{success:false,error:"Monto inválido"};await db.$transaction(async tx=>{await tx.clienteServicio.update({where:{id:actual.id},data:{servicioId:nuevo.id,precioAcordado:p,precioFinal:p,descuentoAplicado:null,notas:[actual.notas,input.motivo?`Cambio de servicio: ${input.motivo}`:null].filter(Boolean).join("\n")||null}});await tx.$executeRaw`INSERT INTO "cliente_servicio_cambio_nexus" ("id","clienteServicioId","servicioAnteriorId","servicioNuevoId","precioAnterior","precioNuevo","motivo","usuarioId","createdAt") VALUES (${crypto.randomUUID()},${actual.id},${actual.servicioId},${nuevo.id},${Number(actual.precioFinal)},${p},${input.motivo?.trim()||null},${s.user.id},NOW())`});return{success:true}}catch(e){console.error(e);return{success:false,error:"No se pudo cambiar el servicio"}}}
export async function obtenerEstadosPago():Promise<ActionResult<Array<{id:string;nombre:string;color:string|null}>>>{try{return{success:true,data:await db.catalogoEstadoPago.findMany({where:{activo:true},select:{id:true,nombre:true,color:true},orderBy:{orden:"asc"}})}}catch(e){console.error(e);return{success:false,error:"Error al obtener estados de pago"}}}
export async function cambiarEstadoPagoServicio(clienteServicioId:string,input:CambiarEstadoPagoFormData):Promise<ActionResult<void>>{try{const v=cambiarEstadoPagoSchema.parse(input);await db.clienteServicio.update({where:{id:clienteServicioId},data:{estadoPagoId:v.estadoPagoId}});return{success:true}}catch(e){console.error(e);return{success:false,error:"Error al cambiar el estado de pago"}}}
