"use client";

import { useEffect,useMemo,useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { ClienteListItem } from "@/types/cliente-types";
import { ClipboardCopy,Search,UserCheck,UserMinus } from "lucide-react";
import { toast } from "sonner";

type AfiliadoRow={clienteId:string;afiliado:boolean;afiliadoAt:string;afiliadoPorNombre:string|null;updatedAt:string};

export function AfiliadosPanel({clientes}:{clientes:ClienteListItem[]}){
 const[rows,setRows]=useState<AfiliadoRow[]>([]),[loading,setLoading]=useState(true),[busqueda,setBusqueda]=useState(""),[guardando,setGuardando]=useState<string|null>(null);
 async function cargar(){setLoading(true);try{const r=await fetch("/api/nexus/afiliados",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error??"No se pudieron cargar afiliados");setRows((j.afiliados??[]) as AfiliadoRow[])}catch(e){toast.error(e instanceof Error?e.message:"No se pudieron cargar afiliados")}finally{setLoading(false)}}
 useEffect(()=>{void cargar()},[]);
 const mapa=useMemo(()=>new Map(rows.map(r=>[r.clienteId,r])),[rows]);
 const q=busqueda.trim().toLowerCase();
 const coincide=(c:ClienteListItem)=>!q||c.nombreCompleto.toLowerCase().includes(q)||c.email?.toLowerCase().includes(q)||c.telefonoCelular?.toLowerCase().includes(q);
 const plenamenteAfiliados=useMemo(()=>clientes.filter(c=>mapa.get(c.id)?.afiliado===true&&coincide(c)),[clientes,mapa,q]);
 const pendientesAfiliacion=useMemo(()=>clientes.filter(c=>c.activo&&mapa.get(c.id)?.afiliado!==true&&coincide(c)),[clientes,mapa,q]);
 async function cambiar(clienteId:string,afiliado:boolean){setGuardando(clienteId);try{const r=await fetch("/api/nexus/afiliados",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clienteId,afiliado})});const j=await r.json();if(!r.ok)throw new Error(j.error??"No se pudo actualizar afiliado");await cargar();toast.success(afiliado?"Cliente convertido en afiliado":"Afiliación retirada")}catch(e){toast.error(e instanceof Error?e.message:"No se pudo actualizar afiliado")}finally{setGuardando(null)}}
 async function copiarAudiencia(){const texto=plenamenteAfiliados.map(c=>`${c.nombreCompleto}\t${c.telefonoCelular??""}\t${c.email??""}`).join("\n");if(!texto){toast.error("No hay afiliados para copiar");return}await navigator.clipboard.writeText(texto);toast.success(`${plenamenteAfiliados.length} contacto(s) copiados para campaña`)}
 const fila=(c:ClienteListItem,es:boolean)=>{const row=mapa.get(c.id);return <div key={c.id} className={`flex flex-col gap-3 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between ${es?"border-violet-200 bg-violet-50/50":"border-amber-200 bg-amber-50/40"}`}><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{c.nombreCompleto}</span>{es?<Badge className="bg-violet-600">PLENAMENTE AFILIADO</Badge>:<Badge variant="outline" className="border-amber-500 text-amber-700">PENDIENTE A AFILIACIÓN</Badge>}</div><div className="mt-1 text-xs text-muted-foreground">{c.telefonoCelular??"Sin teléfono"}{c.email?` · ${c.email}`:""}</div>{row&&<div className="mt-1 text-xs text-muted-foreground">Último cambio: {new Date(row.updatedAt).toLocaleString("es-BO")}{row.afiliadoPorNombre?` · ${row.afiliadoPorNombre}`:""}{es?` · Afiliado desde ${new Date(row.afiliadoAt).toLocaleDateString("es-BO")}`:""}</div>}</div><Button size="sm" variant={es?"outline":"default"} disabled={guardando===c.id} onClick={()=>void cambiar(c.id,!es)}>{es?<><UserMinus className="mr-2 h-4 w-4"/>Quitar afiliación</>:<><UserCheck className="mr-2 h-4 w-4"/>Afiliar cliente</>}</Button></div>};
 return <div className="space-y-6">
  <Card className="border-violet-200 shadow-sm"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><UserCheck className="h-5 w-5 text-violet-600"/>Clientes plenamente afiliados</CardTitle><p className="mt-1 text-sm text-muted-foreground">Clientes históricos o concluidos que ya fueron marcados como afiliados. Permanecen disponibles para campañas, referidos y fidelización.</p></div><div className="flex items-center gap-2"><Badge className="bg-violet-600">{plenamenteAfiliados.length} afiliado(s)</Badge><Button variant="outline" size="sm" onClick={()=>void copiarAudiencia()}><ClipboardCopy className="mr-2 h-4 w-4"/>Copiar audiencia</Button></div></div></CardHeader><CardContent className="space-y-4"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar por nombre, email o teléfono..." value={busqueda} onChange={e=>setBusqueda(e.target.value)}/></div>{loading?<p className="text-sm text-muted-foreground">Cargando afiliados...</p>:<div className="max-h-[420px] space-y-2 overflow-auto pr-1">{plenamenteAfiliados.map(c=>fila(c,true))}{plenamenteAfiliados.length===0&&<div className="rounded-lg border border-dashed p-4 text-center text-sm text-muted-foreground">No hay afiliados que coincidan con la búsqueda.</div>}</div>}</CardContent></Card>
  <Card className="border-amber-200 shadow-sm"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Pendientes a afiliación</CardTitle><p className="mt-1 text-sm text-muted-foreground">Clientes que siguen en gestión operativa y todavía no fueron afiliados. Cuando corresponda, puedes afiliarlos desde aquí.</p></div><Badge variant="outline" className="border-amber-500 text-amber-700">{pendientesAfiliacion.length} pendiente(s)</Badge></div></CardHeader><CardContent>{loading?<p className="text-sm text-muted-foreground">Cargando pendientes...</p>:<div className="max-h-[420px] space-y-2 overflow-auto pr-1">{pendientesAfiliacion.map(c=>fila(c,false))}{pendientesAfiliacion.length===0&&<div className="rounded-lg border border-dashed p-4 text-center text-sm text-muted-foreground">No hay clientes pendientes de afiliación.</div>}</div>}</CardContent></Card>
 </div>
}
