"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, Gauge, Loader2, RotateCcw, ShieldAlert, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ORIGENES_PROSPECTO } from "@/lib/prospectos/origenes";
import { calcularProspectoScore, PROSPECTO_SCORE_QUESTIONS, type ProspectoScoreAnswers } from "@/lib/nexus/prospecto-score";

const initialForm={nombres:"",apellidos:"",telefono:"",ciudad:"",origen:""};
function etiqueta(clasificacion:string){return clasificacion==="ALTA_OPORTUNIDAD"?"ALTA OPORTUNIDAD":clasificacion==="MEDIA_OPORTUNIDAD"?"MEDIA OPORTUNIDAD":"BAJA OPORTUNIDAD"}

export function NexusScoreRapido(){
 const router=useRouter();
 const[respuestas,setRespuestas]=useState<ProspectoScoreAnswers>({});
 const[resultado,setResultado]=useState<{score:number;clasificacion:string}|null>(null);
 const[form,setForm]=useState(initialForm);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
 const respondidas=PROSPECTO_SCORE_QUESTIONS.filter(p=>{const r=respuestas[p.id];return Array.isArray(r)?r.length>0:Boolean(r)}).length;
 const seleccionar=(preguntaId:string,opcion:string,multiple?:boolean,maxSelections=2)=>{if(!multiple){setRespuestas(c=>({...c,[preguntaId]:opcion}));setError("");return}setRespuestas(c=>{const actuales=Array.isArray(c[preguntaId])?c[preguntaId] as string[]:[];if(opcion==="sin_antecedentes")return{...c,[preguntaId]:[opcion]};const sinSin=actuales.filter(v=>v!=="sin_antecedentes");if(sinSin.includes(opcion))return{...c,[preguntaId]:sinSin.filter(v=>v!==opcion)};if(sinSin.length>=maxSelections){setError(`En ANTECEDENTES puedes seleccionar máximo ${maxSelections} opciones.`);return c}setError("");return{...c,[preguntaId]:[...sinSin,opcion]}})};
 const calcular=()=>{const faltantes=PROSPECTO_SCORE_QUESTIONS.filter(p=>{const r=respuestas[p.id];return Array.isArray(r)?r.length===0:!r});if(faltantes.length){setError(`Faltan ${faltantes.length} respuesta(s) para obtener el resultado.`);return}setError("");try{setResultado(calcularProspectoScore(respuestas));window.scrollTo({top:0,behavior:"smooth"})}catch(err){setError(err instanceof Error?err.message:"No se pudo calcular el Score")}};
 const reiniciar=()=>{setRespuestas({});setResultado(null);setForm(initialForm);setError("")};
 const registrar=async(e:React.FormEvent)=>{e.preventDefault();if(!resultado)return;if(!form.nombres.trim()||!form.telefono.trim()){setError("Nombre y teléfono son obligatorios para conservar el resultado.");return}try{setSaving(true);setError("");const r=await fetch("/api/prospectos",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,pais:"Bolivia",interes:"Visa Americana",observaciones:`Captado desde NEXUS Score 2.2 · resultado inicial ${resultado.score}/100`})});const d=await r.json();if(!r.ok){if(r.status===409&&d.duplicado){setError("Esta persona ya existe como prospecto. Ábrela para guardar una nueva evaluación sin duplicarla.");return}throw new Error(d.error||"No se pudo registrar el prospecto")}const prospectoId=d.prospecto.id;const sr=await fetch(`/api/prospectos/${prospectoId}/score`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({respuestas})});const sd=await sr.json();if(!sr.ok)throw new Error(sd.error||"El prospecto se creó, pero no se pudo vincular el Score");router.push(`/prospectos/${prospectoId}`);router.refresh()}catch(err){setError(err instanceof Error?err.message:"No se pudo completar el registro")}finally{setSaving(false)}};
 return <div className="space-y-6">
  <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><div className="flex items-center gap-2"><Gauge className="h-7 w-7 text-blue-700"/><h1 className="text-3xl font-bold tracking-tight">NEXUS Score 2.2</h1></div><p className="mt-1 text-muted-foreground">Evaluación rápida de captación: 9 bloques de perfil + antecedentes al final.</p></div>{resultado&&<Button variant="outline" onClick={reiniciar}><RotateCcw className="mr-2 h-4 w-4"/>Nueva evaluación</Button>}</div>
  {resultado&&<Card className="border-blue-200 bg-blue-50/60"><CardContent className="grid gap-5 pt-6 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-700">Resultado NEXUS Score 2.2</p><div className="mt-2 flex items-end gap-2"><span className="text-5xl font-bold text-slate-950">{resultado.score}</span><span className="pb-1 text-sm text-muted-foreground">/100 pts</span></div><p className="mt-2 text-xl font-bold text-blue-800">{etiqueta(resultado.clasificacion)}</p><p className="mt-2 max-w-2xl text-sm text-slate-600">El resultado parte de los 9 bloques base y descuenta las penalidades seleccionadas en antecedentes.</p></div><div className="rounded-xl border border-blue-200 bg-white p-4 text-sm text-slate-600"><ShieldAlert className="mb-2 h-5 w-5 text-blue-700"/>Índice interno orientativo. No representa ni garantiza aprobación consular.</div></CardContent></Card>}
  {!resultado?<div className="space-y-4">{PROSPECTO_SCORE_QUESTIONS.map((pregunta,index)=><Card key={pregunta.id} className={pregunta.tipo==="PENALIDAD"?"border-amber-200 bg-amber-50/30":""}><CardHeader><CardTitle className="text-base">{index+1}. {pregunta.titulo}</CardTitle><p className="text-sm text-muted-foreground">{pregunta.ayuda}</p>{pregunta.multiple&&<p className="text-xs font-semibold text-amber-700">Máximo {pregunta.maxSelections??2} opciones. “Sin antecedentes” es excluyente.</p>}</CardHeader><CardContent><div className="grid gap-2">{pregunta.opciones.map(opcion=>{const actual=respuestas[pregunta.id];const selected=Array.isArray(actual)?actual.includes(opcion.value):actual===opcion.value;return <button type="button" key={opcion.value} onClick={()=>seleccionar(pregunta.id,opcion.value,pregunta.multiple,pregunta.maxSelections)} className={`flex min-h-12 w-full items-center justify-between gap-3 rounded-lg border p-3 text-left text-sm transition-colors ${selected?pregunta.tipo==="PENALIDAD"?"border-amber-600 bg-amber-50":"border-blue-600 bg-blue-50":"hover:bg-muted/50"}`}><span>{opcion.label}</span><span className="flex shrink-0 items-center gap-2">{pregunta.tipo==="PENALIDAD"&&<span className={`text-xs font-semibold ${opcion.puntos<0?"text-red-600":"text-muted-foreground"}`}>{opcion.puntos} pts</span>}{selected&&<CheckCircle2 className="h-4 w-4 text-blue-700"/>}</span></button>})}</div></CardContent></Card>)}<div className="sticky bottom-4 flex flex-col gap-3 rounded-xl border bg-background/95 p-4 shadow-lg backdrop-blur sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{respondidas} de {PROSPECTO_SCORE_QUESTIONS.length} bloques respondidos</p><p className="text-sm text-muted-foreground">Completa los 10 bloques para mostrar el resultado.</p></div><Button size="lg" onClick={calcular}>Ver mi NEXUS Score</Button></div></div>:
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><UserPlus className="h-5 w-5"/>Guardar resultado como prospecto</CardTitle><p className="text-sm text-muted-foreground">Registra solo los datos esenciales. El Score y todas sus respuestas quedarán vinculados automáticamente.</p></CardHeader><CardContent><form onSubmit={registrar} className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Nombres *</Label><Input value={form.nombres} onChange={e=>setForm(c=>({...c,nombres:e.target.value}))}/></div><div className="space-y-2"><Label>Apellidos</Label><Input value={form.apellidos} onChange={e=>setForm(c=>({...c,apellidos:e.target.value}))}/></div><div className="space-y-2"><Label>Teléfono *</Label><Input value={form.telefono} onChange={e=>setForm(c=>({...c,telefono:e.target.value}))}/></div><div className="space-y-2"><Label>Ciudad</Label><Input value={form.ciudad} onChange={e=>setForm(c=>({...c,ciudad:e.target.value}))}/></div><div className="space-y-2 md:col-span-2"><Label>Fuente / origen</Label><select className="flex h-10 w-full rounded-md border bg-background px-3" value={form.origen} onChange={e=>setForm(c=>({...c,origen:e.target.value}))}><option value="">Selecciona una fuente</option>{ORIGENES_PROSPECTO.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div><div className="md:col-span-2 flex flex-wrap gap-3"><Button type="submit" size="lg" disabled={saving}>{saving?<><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Guardando...</>:"Registrar prospecto y guardar Score"}</Button><Button type="button" variant="outline" onClick={()=>router.push("/prospectos")}>Evaluar prospecto existente</Button></div></form></CardContent></Card>}
  {error&&<div className="rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{error}</div>}
 </div>
}
