export const PROSPECTO_SCORE_VERSION = "NEXUS-SCORE-2.1-GOUSA-2027";

export type ScoreOption = { value:string; label:string; factor:number; puntos:number };
export type ScoreQuestion = { id:string; titulo:string; ayuda:string; peso:number; opciones:ScoreOption[]; tipo?:"BASE"|"PENALIDAD" };
export type ProspectoScoreAnswers = Record<string,string>;
export type ProspectoScoreInsight = { preguntaId:string; titulo:string; respuesta:string; aporte:number; peso:number };
export type ProspectoScoreAnalysis = { prioridadComercial:"ALTA"|"MEDIA"|"BAJA"; fortalezas:ProspectoScoreInsight[]; alertas:ProspectoScoreInsight[]; acciones:string[] };

function opcion(value:string,label:string,puntos:number,peso:number):ScoreOption{return{value,label,puntos,factor:peso===0?(puntos<0?-1:1):puntos/peso}}

export const PROSPECTO_SCORE_QUESTIONS:ScoreQuestion[]=[
 {id:"deportacion_usa",titulo:"¿Tuvo deportación o remoción de Estados Unidos?",ayuda:"Antecedente migratorio de alta relevancia. Registrar únicamente información declarada por la persona.",peso:0,tipo:"PENALIDAD",opciones:[opcion("menos_20","Sí, antecedente confirmado hace menos de 20 años",-25,0),opcion("no","No",0,0)]},
 {id:"estadia_irregular_usa",titulo:"¿Tuvo estadía irregular en Estados Unidos?",ayuda:"Seleccione según cuánto tiempo pasó desde que salió de Estados Unidos.",peso:0,tipo:"PENALIDAD",opciones:[opcion("menos_2","Sí, salió hace menos de 2 años",-25,0),opcion("aprox_5","Sí, salió hace aproximadamente 5 años",-20,0),opcion("5_10","Sí, salió hace 5 a 10 años",-15,0),opcion("mas_10","Sí, salió hace más de 10 años",-10,0),opcion("mas_10_estable","Sí, salió hace más de 10 años y su situación hoy es estable",-3,0),opcion("no","No",0,0)]},
 {id:"negacion_visa_usa",titulo:"¿Tuvo una negación previa de visa de Estados Unidos?",ayuda:"La penalización considera recencia y si hubo cambios relevantes desde la última solicitud.",peso:0,tipo:"PENALIDAD",opciones:[opcion("menos_1_sin_cambios","Sí, hace menos de 1 año y no cambió su situación",-15,0),opcion("2_5_con_cambios","Sí, hace 2 a 5 años y existen cambios",-6,0),opcion("mas_5_con_cambios","Sí, hace más de 5 años y existen cambios",-3,0),opcion("no","No",0,0)]},
 {id:"negacion_otro_pais",titulo:"¿Tuvo negación de visa de otro país?",ayuda:"Considere la negación más reciente declarada.",peso:0,tipo:"PENALIDAD",opciones:[opcion("ultimos_5","Sí, en los últimos 5 años",-5,0),opcion("mas_5","Sí, hace más de 5 años",-2,0),opcion("no","No",0,0)]},
 {id:"vivio_otro_pais",titulo:"¿Vivió o migró en otro país?",ayuda:"Registrar residencia o migración actual o reciente fuera de Bolivia cuando corresponda.",peso:0,tipo:"PENALIDAD",opciones:[opcion("actual_reciente","Sí, actualmente o recientemente",-10,0),opcion("no","No",0,0)]},
 {id:"antecedente_usa",titulo:"¿Tuvo algún otro tipo de antecedente en Estados Unidos?",ayuda:"Incluye antecedentes declarados, detención o situaciones con fianza. Requiere revisión individual antes de cualquier conclusión.",peso:0,tipo:"PENALIDAD",opciones:[opcion("antiguo","Sí, antecedente antiguo",-3,0),opcion("detencion_antecedente","Sí, incluyó detención y antecedente",-22,0),opcion("fianza_sin_problema","Sí, tuvo pago de fianza y no hubo otro problema declarado",-10,0),opcion("no","Sin antecedentes anteriores",0,0)]},
 {id:"estado_civil",titulo:"Estado civil declarado",ayuda:"Registrar la situación actual tal como fue informada por el prospecto.",peso:10,tipo:"BASE",opciones:[opcion("soltero","Soltero(a)",4,10),opcion("casado","Casado(a)",10,10),opcion("divorciado","Divorciado(a)",6,10),opcion("conviviente","Conviviente",8,10)]},
 {id:"hijos",titulo:"Situación de hijos",ayuda:"Seleccionar la alternativa que mejor representa la situación familiar declarada.",peso:5,tipo:"BASE",opciones:[opcion("dependientes","Con hijos dependientes",5,5),opcion("independientes","Con hijos independientes",4,5),opcion("sin_hijos","Sin hijos",1,5)]},
 {id:"situacion_laboral",titulo:"Situación laboral principal",ayuda:"Seleccionar una sola alternativa principal.",peso:15,tipo:"BASE",opciones:[opcion("dependiente_privada_5","Dependiente empresa privada +5 años",7,15),opcion("dependiente_publica_5","Dependiente empresa pública +5 años",15,15),opcion("dependiente_menos_2","Dependiente menos de 2 años",2,15),opcion("independiente_nit_menos_2","Independiente con NIT menos de 2 años",7,15),opcion("independiente_nit_5","Independiente con NIT +5 años",15,15),opcion("independiente_sin_respaldo","Independiente sin respaldo",2,15),opcion("sin_trabajo_renta","Sin trabajo, con renta/propiedades",12,15),opcion("sin_trabajo_patrocinante","Sin trabajo, con patrocinante",5,15),opcion("sin_trabajo_sin_patrocinante","Sin trabajo y sin patrocinante",-10,15)]},
 {id:"antiguedad_laboral",titulo:"Antigüedad / estabilidad laboral",ayuda:"Aplicar a la actividad laboral, empresarial o económica principal cuando corresponda.",peso:15,tipo:"BASE",opciones:[opcion("menos_1","Menos de 1 año",3,15),opcion("menos_2","Estable menos de 2 años",5,15),opcion("3_5","Estable de 3 a 5 años",8,15),opcion("5_10","Estable de 5 a 10 años",12,15),opcion("mas_10","Estable más de 10 años",15,15)]},
 {id:"ingresos",titulo:"Percepción salarial / ingresos mensuales",ayuda:"Usar el ingreso mensual principal declarado y respaldable.",peso:15,tipo:"BASE",opciones:[opcion("hasta_3300","Bs 3.300 o menos",2,15),opcion("3300_6000","Bs 3.300 a Bs 6.000",4,15),opcion("6000_9999","Bs 6.000 a Bs 9.999",9,15),opcion("10000_19999","Bs 10.000 a Bs 19.999",12,15),opcion("20000_mas","Bs 20.000 o más",15,15)]},
 {id:"vivienda",titulo:"Vivienda / estabilidad residencial",ayuda:"Seleccionar la condición residencial principal.",peso:10,tipo:"BASE",opciones:[opcion("propiedad","Propiedad inmueble a su nombre",10,10),opcion("anticretico","Anticrético",5,10),opcion("alquiler_menor_2500","Alquiler hasta Bs 2.500",3,10),opcion("alquiler_3000_mas","Alquiler Bs 3.000 o más",4,10),opcion("vive_padres","Vive con padres",2,10)]},
 {id:"solidez_financiera",titulo:"Principal señal patrimonial / financiera",ayuda:"Elegir la señal que mejor represente la situación actual.",peso:10,tipo:"BASE",opciones:[opcion("otro_patrimonio","Otro patrimonio a su nombre",7,10),opcion("cuentas_bancarias","Cuentas bancarias con ahorro/movimiento",10,10),opcion("efectivo_ahorrado","Dinero en efectivo ahorrado",6,10),opcion("deuda_alta_productiva","Deuda bancaria alta vinculada a negocio/propiedad",10,10),opcion("deuda_baja","Deuda bancaria baja",4,10),opcion("sin_deuda_sin_bienes","Sin deuda pero sin bienes",-10,10)]},
 {id:"entorno_usa",titulo:"Contexto de viaje / vínculos en Estados Unidos",ayuda:"Registrar la situación que mejor describa el contexto principal del viaje.",peso:10,tipo:"BASE",opciones:[opcion("familiar_ciudadano","Familiar de primer grado ciudadano estadounidense",8,10),opcion("evento_feria","Invitación a evento o feria en Estados Unidos",10,10),opcion("amistad_legal","Amistad o conocido en Estados Unidos con estatus legal",6,10),opcion("sin_conocido_respaldo","Sin conocido en Estados Unidos, pero con respaldos de viaje",8,10),opcion("familiar_directo_irregular","Familiar directo en Estados Unidos con situación migratoria irregular",-20,10)]},
 {id:"historial_viajes",titulo:"Historial de viajes al exterior",ayuda:"Seleccionar la alternativa que mejor resuma el historial internacional declarado.",peso:10,tipo:"BASE",opciones:[opcion("mas_2_ultimos_5","Más de 2 países visitados en los últimos 5 años",10,10),opcion("2_ultimos_5","2 países visitados en los últimos 5 años",7,10),opcion("mas_5_historicos","Más de 5 viajes al exterior realizados históricamente",5,10),opcion("ninguno","Ningún viaje al exterior",1,10)]}
];

export function calcularProspectoScore(respuestas:ProspectoScoreAnswers){let score=0;for(const pregunta of PROSPECTO_SCORE_QUESTIONS){const seleccion=pregunta.opciones.find(i=>i.value===respuestas[pregunta.id]);if(!seleccion)throw new Error(`Respuesta inválida para ${pregunta.id}`);score+=seleccion.puntos}const scoreNormalizado=Math.max(0,Math.min(100,Math.round(score)));return{score:scoreNormalizado,clasificacion:clasificarProspectoScore(scoreNormalizado)}}
export function analizarProspectoScore(respuestas:ProspectoScoreAnswers):ProspectoScoreAnalysis{const items=PROSPECTO_SCORE_QUESTIONS.map(p=>{const s=p.opciones.find(i=>i.value===respuestas[p.id]);if(!s)throw new Error(`Respuesta inválida para ${p.id}`);return{preguntaId:p.id,titulo:p.titulo,respuesta:s.label,aporte:s.puntos,peso:p.peso,factor:s.factor,tipo:p.tipo}});const fortalezas=items.filter(i=>i.tipo!=="PENALIDAD"&&i.factor>=.75).sort((a,b)=>b.aporte-a.aporte).slice(0,4).map(({factor:_f,tipo:_t,...i})=>i);const alertas=items.filter(i=>i.aporte<0).sort((a,b)=>a.aporte-b.aporte).slice(0,6).map(({factor:_f,tipo:_t,...i})=>i);const acciones=alertas.map(a=>a.tipo==="PENALIDAD"?`Revisar antecedente migratorio antes de avanzar: ${a.titulo}.`:`Revisar: ${a.titulo}.`);const{score}=calcularProspectoScore(respuestas);const prioridadComercial=score>=70?"ALTA":score>=45?"MEDIA":"BAJA";return{prioridadComercial,fortalezas,alertas,acciones:[...new Set(acciones)].slice(0,6)} as ProspectoScoreAnalysis}
export function clasificarProspectoScore(score:number){if(score>=70)return"ALTA_OPORTUNIDAD";if(score>=45)return"MEDIA_OPORTUNIDAD";return"BAJA_OPORTUNIDAD"}
export function validarRespuestasProspectoScore(respuestas:ProspectoScoreAnswers){return PROSPECTO_SCORE_QUESTIONS.every(p=>p.opciones.some(o=>o.value===respuestas[p.id]))}
