"use server";
import{headers}from"next/headers";import{auth}from"@/lib/auth";import{db}from"@/lib/db";import{registrarAuditoriaNexus}from"@/lib/auditoria-nexus";import type{ActionResult}from"@/types/action-result-types";import{trabajoAnteriorSchema,estudioAnteriorSchema,type TrabajoAnteriorFormData,type EstudioAnteriorFormData}from"@/validations/cliente-validations";

export async function asegurarTablasHistorialFormativo(){await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "cliente_trabajo_anterior_nexus" ("id" TEXT PRIMARY KEY,"clienteId" TEXT NOT NULL REFERENCES "cliente"("id") ON DELETE CASCADE,"lugar" TEXT NOT NULL,"fechaIngreso" DATE,"fechaSalida" DATE,"cargo" TEXT,"descripcion" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS "cliente_trabajo_anterior_nexus_cliente_idx" ON "cliente_trabajo_anterior_nexus"("clienteId");CREATE TABLE IF NOT EXISTS "cliente_estudio_anterior_nexus" ("id" TEXT PRIMARY KEY,"clienteId" TEXT NOT NULL REFERENCES "cliente"("id") ON DELETE CASCADE,"lugar" TEXT NOT NULL,"direccion" TEXT,"carrera" TEXT,"fechaIngreso" DATE,"fechaFinalizacion" DATE,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS "cliente_estudio_anterior_nexus_cliente_idx" ON "cliente_estudio_anterior_nexus"("clienteId");`)}

export type TrabajoAnteriorItem=TrabajoAnteriorFormData&{id:string;createdAt:Date};export type EstudioAnteriorItem=EstudioAnteriorFormData&{id:string;createdAt:Date};
export async function obtenerHistorialFormativo(clienteId:string):Promise<ActionResult<{trabajos:TrabajoAnteriorItem[];estudios:EstudioAnteriorItem[]}>>{try{await asegurarTablasHistorialFormativo();const[trabajos,estudios]=await Promise.all([db.$queryRaw<TrabajoAnteriorItem[]>`SELECT "id","lugar","fechaIngreso","fechaSalida","cargo","descripcion","createdAt" FROM "cliente_trabajo_anterior_nexus" WHERE "clienteId"=${clienteId} ORDER BY COALESCE("fechaSalida","fechaIngreso") DESC NULLS LAST,"createdAt" DESC`,db.$queryRaw<EstudioAnteriorItem[]>`SELECT "id","lugar","direccion","carrera","fechaIngreso","fechaFinalizacion","createdAt" FROM "cliente_estudio_anterior_nexus" WHERE "clienteId"=${clienteId} ORDER BY COALESCE("fechaFinalizacion","fechaIngreso") DESC NULLS LAST,"createdAt" DESC`]);return{success:true,data:{trabajos,estudios}}}catch(e){console.error(e);return{success:false,error:"No se pudo cargar el historial"}}}
export async function agregarTrabajoAnterior(clienteId:string,input:TrabajoAnteriorFormData):Promise<ActionResult<void>>{try{await asegurarTablasHistorialFormativo();const s=await auth.api.getSession({headers:await headers()});if(!s?.user?.id)return{success:false,error:"No autorizado"};const v=trabajoAnteriorSchema.parse(input);await db.$executeRaw`INSERT INTO "cliente_trabajo_anterior_nexus" ("id","clienteId","lugar","fechaIngreso","fechaSalida","cargo","descripcion","createdAt") VALUES (${crypto.randomUUID()},${clienteId},${v.lugar},${v.fechaIngreso?new Date(v.fechaIngreso):null},${v.fechaSalida?new Date(v.fechaSalida):null},${v.cargo||null},${v.descripcion||null},NOW())`;await registrarAuditoriaNexus({accion:"TRABAJO ANTERIOR AGREGADO",entidad:"Cliente",entidadId:clienteId,clienteId,usuarioId:s.user.id,detalle:v.lugar});return{success:true}}catch(e){console.error(e);return{success:false,error:"No se pudo agregar el trabajo anterior"}}}
export async function agregarEstudioAnterior(clienteId:string,input:EstudioAnteriorFormData):Promise<ActionResult<void>>{try{await asegurarTablasHistorialFormativo();const s=await auth.api.getSession({headers:await headers()});if(!s?.user?.id)return{success:false,error:"No autorizado"};const v=estudioAnteriorSchema.parse(input);await db.$executeRaw`INSERT INTO "cliente_estudio_anterior_nexus" ("id","clienteId","lugar","direccion","carrera","fechaIngreso","fechaFinalizacion","createdAt") VALUES (${crypto.randomUUID()},${clienteId},${v.lugar},${v.direccion||null},${v.carrera||null},${v.fechaIngreso?new Date(v.fechaIngreso):null},${v.fechaFinalizacion?new Date(v.fechaFinalizacion):null},NOW())`;await registrarAuditoriaNexus({accion:"ESTUDIO ANTERIOR AGREGADO",entidad:"Cliente",entidadId:clienteId,clienteId,usuarioId:s.user.id,detalle:v.lugar});return{success:true}}catch(e){console.error(e);return{success:false,error:"No se pudo agregar el estudio anterior"}}}
export async function eliminarHistorialFormativo(clienteId:string,tipo:"TRABAJO"|"ESTUDIO",id:string):Promise<ActionResult<void>>{try{await asegurarTablasHistorialFormativo();const s=await auth.api.getSession({headers:await headers()});if(!s?.user?.id)return{success:false,error:"No autorizado"};if(tipo==="TRABAJO")await db.$executeRaw`DELETE FROM "cliente_trabajo_anterior_nexus" WHERE "id"=${id} AND "clienteId"=${clienteId}`;else await db.$executeRaw`DELETE FROM "cliente_estudio_anterior_nexus" WHERE "id"=${id} AND "clienteId"=${clienteId}`;await registrarAuditoriaNexus({accion:`${tipo} ANTERIOR ELIMINADO`,entidad:"Cliente",entidadId:clienteId,clienteId,usuarioId:s.user.id});return{success:true}}catch(e){console.error(e);return{success:false,error:"No se pudo eliminar el antecedente"}}}
