"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import { AlertTriangle,CalendarPlus,CheckCircle2,ClipboardCheck,RefreshCcw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";

type Pendiente={id:string;titulo:string;detalle:string|null;categoria:string;fechaObjetivo:string;asignadoA:string|null;prospecto:string|null;cliente:string|null;diaOffset:number;atrasado:boolean};
type Usuario={id:string;name:string};
const CATEGORIAS=[
  ["CIERRE_PROSPECTO","Cerrar / dar seguimiento a prospecto"],
  ["DOCUMENTOS","Solicitar o revisar documentos"],
  ["PAGO","Cobro / pago pendiente"],
  ["LLAMADA","Llamar o contactar"],
  ["OTRO","Otro pendiente"],
] as const;

function fechaBolivia(offset=0){const d=new Date(new Date().toLocaleString("en-US",{timeZone:"America/La_Paz"}));d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function etiquetaFecha(offset:number){const nombre=offset===0?"HOY":offset===1?"MAÑANA":offset===2?"PASADO MAÑANA":"ATRASADOS";const d=new Date(new Date().toLocaleString("en-US",{timeZone:"America/La_Paz"}));d.setDate(d.getDate()+Math.max(offset,0));return `${nombre} (${String(d.getDate()).padStart(2,"0")}/${d.toLocaleString("es-BO",{month:"short",timeZone:"America/La_Paz"}).replace(".","")})`;}

export function PendientesTimeCard(){
 const[pendientes,setPendientes]=useState<Pendiente[]>([]),[usuarios,setUsuarios]=useState<Usuario[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false);
 const[titulo,setTitulo]=useState(""),[detalle,setDetalle]=useState(""),[categoria,setCategoria]=useState("CIERRE_PROSPECTO"),[fechaObjetivo,setFechaObjetivo]=useState(fechaBolivia()),[asignadoAId,setAsignadoAId]=useState("SIN_ASIGNAR");
 const cargar=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/nexus/pendientes",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error??"No se pudieron cargar los pendientes");setPendientes(j.pendientes??[]);setUsuarios(j.usuarios??[]);setError(null)}catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar los pendientes")}finally{setLoading(false)}},[]);
 useEffect(()=>{void cargar()},[cargar]);
 const grupos=useMemo(()=>({atrasados:pendientes.filter(p=>p.diaOffset<0),hoy:pendientes.filter(p=>p.diaOffset===0),manana:pendientes.filter(p=>p.diaOffset===1),pasado:pendientes.filter(p=>p.diaOffset===2)}),[pendientes]);
 async function crear(){if(!titulo.trim())return;setSaving(true);setError(null);try{const r=await fetch("/api/nexus/pendientes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({titulo:titulo.trim(),detalle:detalle.trim()||null,categoria,fechaObjetivo,asignadoAId:asignadoAId==="SIN_ASIGNAR"?null:asignadoAId})});const j=await r.json();if(!r.ok)throw new Error(j.error??"No se pudo crear el pendiente");setTitulo("");setDetalle("");setFechaObjetivo(fechaBolivia());await cargar()}catch(e){setError(e instanceof Error?e.message:"No se pudo crear el pendiente")}finally{setSaving(false)}}
 async function completar(id:string){setError(null);try{const r=await fetch(`/api/nexus/pendientes/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({completado:true})});const j=await r.json();if(!r.ok)throw new Error(j.error??"No se pudo completar el pendiente");setPendientes(actual=>actual.filter(p=>p.id!==id))}catch(e){setError(e instanceof Error?e.message:"No se pudo completar el pendiente")}}
 const render=(items:Pendiente[],tituloGrupo:string,atrasado=false)=><div className="space-y-2"><div className={`text-xs font-semibold uppercase tracking-wide ${atrasado?"text-red-600":"text-muted-foreground"}`}>{tituloGrupo}</div>{items.length===0?<div className="rounded-lg border border-dashed p-3 text-center text-sm text-muted-foreground">Sin pendientes.</div>:items.map(p=><div key={p.id} className={`rounded-lg border p-3 ${atrasado?"border-red-300 bg-red-50/60":""}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{p.titulo}</span><Badge variant={atrasado?"destructive":"secondary"}>{CATEGORIAS.find(c=>c[0]===p.categoria)?.[1]??p.categoria}</Badge>{atrasado&&<AlertTriangle className="h-4 w-4 text-red-600"/>}</div>{p.detalle&&<p className="mt-1 text-sm text-muted-foreground">{p.detalle}</p>}<div className="mt-1 text-xs text-muted-foreground">{p.cliente??p.prospecto??"Sin persona vinculada"}{p.asignadoA?` · Responsable: ${p.asignadoA}`:" · Sin responsable"}</div></div><Button size="sm" variant="outline" onClick={()=>void completar(p.id)}><CheckCircle2 className="mr-1.5 h-4 w-4"/>Completar</Button></div></div>)}</div>;
 return <Card className="border-amber-200 shadow-sm"><CardHeader className="pb-3"><div className="flex items-center justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-base"><ClipboardCheck className="h-5 w-5"/>Pendientes con fecha</CardTitle><p className="mt-1 text-xs text-muted-foreground">Acciones compartidas del equipo que deben ejecutarse en una fecha concreta.</p></div><Button variant="outline" size="sm" onClick={()=>void cargar()} disabled={loading}><RefreshCcw className="mr-2 h-4 w-4"/>Actualizar</Button></div></CardHeader><CardContent className="space-y-5">{error&&<div className="rounded-md border border-red-200 bg-red-50 p-2 text-sm text-red-700">{error}</div>}<div className="rounded-xl border bg-muted/20 p-4"><div className="mb-3 flex items-center gap-2 text-sm font-semibold"><CalendarPlus className="h-4 w-4"/>Nuevo pendiente</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="xl:col-span-2"><Label>Título</Label><Input value={titulo} onChange={e=>setTitulo(e.target.value)} placeholder="Ej. Llamar a Juan para cerrar solicitud"/></div><div><Label>Fecha</Label><Input type="date" value={fechaObjetivo} onChange={e=>setFechaObjetivo(e.target.value)}/></div><div><Label>Tipo</Label><Select value={categoria} onValueChange={setCategoria}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{CATEGORIAS.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div><div className="xl:col-span-2"><Label>Detalle opcional</Label><Input value={detalle} onChange={e=>setDetalle(e.target.value)} placeholder="Nota breve para el equipo"/></div><div><Label>Responsable</Label><Select value={asignadoAId} onValueChange={setAsignadoAId}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="SIN_ASIGNAR">Todo el equipo</SelectItem>{usuarios.map(u=><SelectItem key={u.id} value={u.id}>{u.name}</SelectItem>)}</SelectContent></Select></div><div className="flex items-end"><Button className="w-full" onClick={()=>void crear()} disabled={saving||!titulo.trim()}>{saving?"Guardando...":"Agregar pendiente"}</Button></div></div></div>{loading&&pendientes.length===0?<p className="text-sm text-muted-foreground">Cargando pendientes...</p>:<div className="grid gap-5 xl:grid-cols-2">{render(grupos.atrasados,"ATRASADOS",true)}{render(grupos.hoy,etiquetaFecha(0))}{render(grupos.manana,etiquetaFecha(1))}{render(grupos.pasado,etiquetaFecha(2))}</div>}</CardContent></Card>;
}
