import { NextResponse } from "next/server";

const AIRPORTS_URL="https://cdn.jsdelivr.net/gh/srestre/world-countries-cities-db@main/airports/airports.json";
type AirportSource={ident?:string;type?:string;name?:string;iata?:string;icao?:string;iso_country?:string;municipality?:string};
type AirportResult={iata:string;name:string;city:string;country:string};
const FALLBACK:AirportResult[]=[{iata:"LPB",name:"El Alto International Airport",city:"La Paz",country:"BO"},{iata:"VVI",name:"Viru Viru International Airport",city:"Santa Cruz",country:"BO"},{iata:"CBB",name:"Jorge Wilstermann International Airport",city:"Cochabamba",country:"BO"},{iata:"MIA",name:"Miami International Airport",city:"Miami",country:"US"},{iata:"JFK",name:"John F Kennedy International Airport",city:"New York",country:"US"},{iata:"LAX",name:"Los Angeles International Airport",city:"Los Angeles",country:"US"},{iata:"MCO",name:"Orlando International Airport",city:"Orlando",country:"US"},{iata:"IAD",name:"Washington Dulles International Airport",city:"Washington DC",country:"US"},{iata:"ATL",name:"Hartsfield Jackson Atlanta International Airport",city:"Atlanta",country:"US"},{iata:"MAD",name:"Adolfo Suárez Madrid–Barajas Airport",city:"Madrid",country:"ES"}];
let memoryCache:AirportResult[]|null=null;
function normalize(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim()}
async function loadAirports():Promise<AirportResult[]>{if(memoryCache)return memoryCache;try{const r=await fetch(AIRPORTS_URL,{next:{revalidate:86400}});if(!r.ok)throw new Error(`Airport catalog ${r.status}`);const source=(await r.json()) as AirportSource[];const seen=new Set<string>();memoryCache=source.map(a=>({iata:(a.iata??"").trim().toUpperCase(),name:(a.name??"").trim(),city:(a.municipality??"").trim(),country:(a.iso_country??"").trim().toUpperCase()})).filter(a=>{if(!/^[A-Z0-9]{3}$/.test(a.iata)||seen.has(a.iata))return false;seen.add(a.iata);return true});return memoryCache}catch(e){console.error("No se pudo cargar el catálogo mundial de aeropuertos:",e);return FALLBACK}}
export async function GET(request:Request){const{searchParams}=new URL(request.url);const raw=searchParams.get("q")??"";const query=normalize(raw);if(query.length<2)return NextResponse.json({aeropuertos:[]});const airports=await loadAirports();const exactIata=raw.trim().toUpperCase();if(/^[A-Z0-9]{3}$/.test(exactIata)){const exact=airports.find(a=>a.iata===exactIata)??FALLBACK.find(a=>a.iata===exactIata);if(exact)return NextResponse.json({aeropuertos:[exact]},{headers:{"Cache-Control":"public, s-maxage=86400, stale-while-revalidate=604800"}})}const scored=airports.map(airport=>{const iata=normalize(airport.iata),city=normalize(airport.city),name=normalize(airport.name);let score=99;if(iata===query)score=0;else if(iata.startsWith(query))score=1;else if(city===query)score=2;else if(city.startsWith(query))score=3;else if(name.startsWith(query))score=4;else if(city.includes(query))score=5;else if(name.includes(query))score=6;else if(iata.includes(query))score=7;return{airport,score}}).filter(x=>x.score<99).sort((a,b)=>a.score-b.score||a.airport.iata.localeCompare(b.airport.iata)).slice(0,12).map(x=>x.airport);return NextResponse.json({aeropuertos:scored},{headers:{"Cache-Control":"public, s-maxage=86400, stale-while-revalidate=604800"}})}