"use server";
import{headers}from"next/headers";import{auth}from"@/lib/auth";import{db}from"@/lib/db";import type{ActionResult}from"@/types/action-result-types";
export type VentaRapidaNexus={id:string;nombrePersona:string;telefono:string|null;servicioId:string|null;servicioNombre:string;cantidad:number;tarifaBase:number|null;montoServicio:number;montoCobrado:number;estadoPago:"PENDIENTE"|"PARCIAL"|"PAGADO";modalidadPago:string|null;responsableId:string;responsableNombre:string|null;registradoPorNombre:string|null;observacion:string|null;solicitaFactura:boolean;nombreRazonSocial:string|null;nit:string|null;facturaEmitida:boolean;facturaEmitidaAt:string|null;createdAt:string};
export const CATALOGO_VENTA_RAPIDA=[
{id:"REC_CTA_IMP",nombre:"Recuperación de Cuenta e Impresión",tarifa:150},
{id:"IMP_CONFIRM",nombre:"Impresión de Confirmación",tarifa:10},
{id:"RASTREO_CTA",nombre:"Rastreo de Cuenta",tarifa:100},
{id:"ENVIO_INTERIOR",nombre:"Envío de Documentación al Interior",tarifa:120},
{id:"ASES_MIG_30",nombre:"Asesoría Migratoria 30 Minutos",tarifa:200},
{id:"ASES_MIG_30_50",nombre:"Asesoría Migratoria 30 a 50 Minutos",tarifa:300},
{id:"ASES_ULT_HORA",nombre:"Asesoría de Última Hora",tarifa:250},
{id:"SIM_CABINA",nombre:"Simulacro en Cabina Centro Simulación Consular",tarifa:450},
{id:"LLENADO_FORM",nombre:"Llenado de Formulario",tarifa:350},
{id:"ESTA",nombre:"Solicitud ESTA",tarifa:200},
{id:"REV_CASO",nombre:"Revisión de Caso e Interpretación",tarifa:200},
{id:"OTRO",nombre:"Otro Servicio – Detallar",tarifa:null},
] as const;
async function ensure(){await db.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "venta_rapida_nexus"("id" TEXT PRIMARY KEY,"nombrePersona" TEXT NOT NULL,"telefono" TEXT,"servicioId" TEXT REFERENCES "catalogo_servicio"("id") ON DELETE SET NULL,"servicioNombre" TEXT NOT NULL,"montoServicio" DECIMAL(12,2) NOT NULL,"montoCobrado" DECIMAL(12,2) NOT NULL DEFAULT 0,"estadoPago" TEXT NOT NULL DEFAULT 'PENDIENTE',"modalidadPago" TEXT,"responsableId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE RESTRICT,"registradoPorId" TEXT REFERENCES "user"("id") ON DELETE SET NULL,"observacion" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CHECK ("estadoPago" IN ('PENDIENTE','PARCIAL','PAGADO')))`);for(const q of[`ALTER TABLE "venta_rapida_nexus" ADD COLUMN IF NOT EXISTS "solicitaFactura" BOOLEAN NOT NULL DEFAULT false`,`ALTER TABLE "venta_rapida_nexus" ADD COLUMN IF NOT EXISTS "nombreRazonSocial" TEXT`,`ALTER TABLE "venta_rapida_nexus" ADD COLUMN IF NOT EXISTS "nit" TEXT`,`ALTER TABLE "venta_rapida_nexus" ADD COLUMN IF NOT EXISTS "facturaEmitida" BOOLEAN NOT NULL DEFAULT false`,`ALTER TABLE "venta_rapida_nexus" ADD COLUMN IF NOT EXISTS "facturaEmitidaAt" TIMESTAMP(3)`,`ALTER TABLE "venta_rapida_nexus" ADD COLUMN IF NOT EXISTS "facturaEmitidaPorId" TEXT`,`ALTER TABLE "venta_rapida_nexus" ADD COLUMN IF NOT EXISTS "cantidad" INTEGER NOT NULL DEFAULT 1`,`ALTER TABLE "venta_rapida_nexus" ADD COLUMN IF NOT EXISTS "tarifaBase" DECIMAL(12,2)`])await db.$executeRawUnsafe(q);await db.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "venta_rapida_nexus_fecha_idx" ON "venta_rapida_nexus"("createdAt" DESC)`);await db.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "venta_rapida_nexus_responsable_idx" ON "venta_rapida_nexus"("responsableId")`)}
async function sesion(){return auth.api.getSession({headers:await headers()})}
export async function obtenerCatalogoVentaRapida():Promise<ActionResult<{servicios:Array<{id:string;nombre:string;tarifa:number|null}>;usuarios:Array<{id:string;name:string}>}>>{try{const s=await sesion();if(!s?.user?.id)return{success:false,error:"No autorizado"};const usuarios=await db.user.findMany({select:{id:true,name:true},orderBy:{name:"asc"}});return{success:true,data:{servicios:CATALOGO_VENTA_RAPIDA.map(x=>({...x})),usuarios:usuarios.map(u=>({id:u.id,name:u.name??"Usuario"}))}}}catch(e){console.error(e);return{success:false,error:"No se pudo cargar el catálogo"}}}
export async function crearVentaRapida(input:{nombrePersona:string;telefono?:string;servicioId:string;servicioNombre?:string;cantidad:number;montoServicio:number;montoCobrado:number;modalidadPago?:"EFECTIVO"|"QR"|"TRANSFERENCIA"|null;responsableId:string;observacion?:string;solicitaFactura:boolean;nombreRazonSocial?:string;nit?:string}):Promise<ActionResult<{id:string;estadoPago:"PENDIENTE"|"PARCIAL"|"PAGADO";servicioNombre:string;monto:number;fecha:string}>>{try{await ensure();const s=await sesion();if(!s?.user?.id)return{success:false,error:"No autorizado"};const nombre=input.nombrePersona.trim();if(!nombre)return{success:false,error:"Ingresa el nombre de la persona"};const item=CATALOGO_VENTA_RAPIDA.find(x=>x.id===input.servicioId);if(!item)return{success:false,error:"Servicio rápido no válido"};const cantidad=Math.max(1,Math.trunc(Number(input.cantidad)||1));const total=Number(input.montoServicio),cobrado=Number(input.montoCobrado);if(!Number.isFinite(total)||total<=0)return{success:false,error:"Ingresa un monto de servicio válido"};if(!Number.isFinite(cobrado)||cobrado<0||cobrado>total)return{success:false,error:"El monto cobrado debe estar entre 0 y el total"};if(cobrado>0&&!input.modalidadPago)return{success:false,error:"Selecciona modalidad de pago"};const estado:"PENDIENTE"|"PARCIAL"|"PAGADO"=cobrado<=0?"PENDIENTE":cobrado+0.001>=total?"PAGADO":"PARCIAL";if(input.solicitaFactura&&estado!=="PAGADO")return{success:false,error:"La factura solo puede solicitarse cuando el servicio está pagado por completo"};if(input.solicitaFactura&&(!input.nombreRazonSocial?.trim()||!input.nit?.trim()))return{success:false,error:"Completa Nombre / Razón Social y NIT para facturación"};const resp=await db.user.findUnique({where:{id:input.responsableId},select:{id:true}});if(!resp)return{success:false,error:"Responsable no válido"};const servicioNombre=item.id==="OTRO"?(input.servicioNombre??"").trim():item.nombre;if(!servicioNombre)return{success:false,error:"Detalla el otro servicio"};const id=crypto.randomUUID();await db.$executeRaw`INSERT INTO "venta_rapida_nexus"("id","nombrePersona","telefono","servicioId","servicioNombre","cantidad","tarifaBase","montoServicio","montoCobrado","estadoPago","modalidadPago","responsableId","registradoPorId","observacion","solicitaFactura","nombreRazonSocial","nit","createdAt","updatedAt") VALUES(${id},${nombre},${input.telefono?.trim()||null},${null},${servicioNombre},${cantidad},${item.tarifa},${total},${cobrado},${estado},${input.modalidadPago??null},${input.responsableId},${s.user.id},${input.observacion?.trim()||null},${input.solicitaFactura},${input.nombreRazonSocial?.trim()||null},${input.nit?.trim()||null},NOW(),NOW())`;return{success:true,data:{id,estadoPago:estado,servicioNombre,monto:total,fecha:new Date().toLocaleDateString("es-BO")}}}catch(e){console.error("crearVentaRapida",e);return{success:false,error:"No se pudo registrar la venta rápida"}}}
export async function marcarFacturaEmitidaVentaRapida(id:string,emitida:boolean):Promise<ActionResult<void>>{try{await ensure();const s=await sesion();if(!s?.user?.id)return{success:false,error:"No autorizado"};const rows=await db.$queryRaw<Array<any>>`SELECT * FROM "venta_rapida_nexus" WHERE "id"=${id} LIMIT 1`;const v=rows[0];if(!v)return{success:false,error:"Venta no encontrada"};if(emitida&&!v.solicitaFactura)return{success:false,error:"La venta no está marcada para facturación"};if(emitida&&v.estadoPago!=="PAGADO")return{success:false,error:"Primero confirma el pago completo"};await db.$executeRaw`UPDATE "venta_rapida_nexus" SET "facturaEmitida"=${emitida},"facturaEmitidaAt"=${emitida?new Date():null},"facturaEmitidaPorId"=${emitida?s.user.id:null},"updatedAt"=NOW() WHERE "id"=${id}`;return{success:true}}catch(e){console.error(e);return{success:false,error:"No se pudo actualizar la factura"}}}
export async function obtenerVentasRapidas():Promise<ActionResult<{items:VentaRapidaNexus[];resumen:{totalServicios:number;totalCobrado:number;saldo:number}}>>{try{await ensure();const s=await sesion();if(!s?.user?.id)return{success:false,error:"No autorizado"};const rows=await db.$queryRaw<Array<any>>`SELECT v.*,r."name" AS "responsableNombre",u."name" AS "registradoPorNombre" FROM "venta_rapida_nexus" v LEFT JOIN "user" r ON r."id"=v."responsableId" LEFT JOIN "user" u ON u."id"=v."registradoPorId" ORDER BY v."createdAt" DESC LIMIT 300`;const items:VentaRapidaNexus[]=rows.map(x=>({id:x.id,nombrePersona:x.nombrePersona,telefono:x.telefono,servicioId:x.servicioId,servicioNombre:x.servicioNombre,cantidad:Number(x.cantidad??1),tarifaBase:x.tarifaBase==null?null:Number(x.tarifaBase),montoServicio:Number(x.montoServicio),montoCobrado:Number(x.montoCobrado),estadoPago:x.estadoPago,modalidadPago:x.modalidadPago,responsableId:x.responsableId,responsableNombre:x.responsableNombre,registradoPorNombre:x.registradoPorNombre,observacion:x.observacion,solicitaFactura:Boolean(x.solicitaFactura),nombreRazonSocial:x.nombreRazonSocial,nit:x.nit,facturaEmitida:Boolean(x.facturaEmitida),facturaEmitidaAt:x.facturaEmitidaAt?new Date(x.facturaEmitidaAt).toISOString():null,createdAt:new Date(x.createdAt).toISOString()}));const totalServicios=items.reduce((a,x)=>a+x.montoServicio,0),totalCobrado=items.reduce((a,x)=>a+x.montoCobrado,0);return{success:true,data:{items,resumen:{totalServicios,totalCobrado,saldo:Math.max(0,totalServicios-totalCobrado)}}}}catch(e){console.error(e);return{success:false,error:"No se pudieron cargar las ventas rápidas"}}}
